export const subjectList = [
  'Kittens',
  'Bad pictures',
  'Ugly fonts',
  'Netflix',
  'Facebook fans',
  'Instagram follower',
  'Twitter',
  'Entire Google Database',
  'Selfies',
  'Cats',
  'Chihuahuas',
  'Fake news',
  'Whale screams',
  'Sunglasses',
  'Twelve legged dogs',
  'Grandmas fennel salad',
  'Colours',
  'Brussel Sprouts',
  'Irrelevant questions',
  'Preposterous ',
  'TV Shows',
  'Britney Spears',
  'Surroundings',
  'Security restrictions',
  'User webcam without consent',
  'User Credit card',
];
